### ISSUE TITLE
https

### ISSUE THREAD

**Issue by elof** [Macrometacorp/tutorial-addressbook-streams#5]
The live demo app needs to be hosted behind a CDN (using Github pages makes sense to me) and https need to be enforced

**Comment by yyovkov** [comment]
GitHub pages enabled for the repository https://github.com/Macrometacorp/tutorial-addressbook-streams.

**Comment by dwivedianurag** [comment]
@elof I have published the site via gh-pages https://macrometacorp.github.io/tutorial-addressbook-streams/. If you find this ok I will update the readme and subsequently other pages and ask the sre team to undeploy these websites from s3 bucket

**Comment by elof** [comment]
👍
